export const CART_ACTIONS = {
  ADD_TO_CART: "ADD_TO_CART",
  ADD_BUNDLED_PRODUCT_TO_CART: "ADD_BUNDLED_PRODUCT_TO_CART",
  CLEAR_CART: "CLEAR_CART",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  POPULATE_CART: "POPULATE_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  SET_QUANTITY: "SET_QUANTITY",
};
